# Generated by Django 4.2.2 on 2023-06-23 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_hasgtag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HasgTag',
            new_name='HashTag',
        ),
    ]
